myapp/urls.py
from django.urls import path
from myapp import views
from django.urls import include
from django.urls import path

app_name = 'myapp'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:top_no>/', views.detail, name='detail'),
    path(r'courses/', views.courses, name='courses'),
    path(r'courses/<int:cour_id>/', views.coursedetail, name='coursedetail'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'login/', views.user_login, name='login'),
    path(r'logout/', views.user_logout, name='logout'),
    path(r'myaccount/', views.myaccount, name='myaccount'),
]

mywebappS22/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
]

myapp/models.py
import decimal

from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone

from django.core.validators import MinValueValidator
from django.core.validators import MaxValueValidator


# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200, default="")

    def __str__(self):
        return "%s %s" % (self.name, self.category)


class Course(models.Model):
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    # final project q9
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(50.00), MaxValueValidator(500.00)])
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)
    interested = models.PositiveIntegerField(default=0)
    stages = models.PositiveIntegerField(default=3)

    def __str__(self):
        return "%s" % (self.name)

    def discount(self):
        disc_price = self.price - decimal.Decimal((float(self.price)*0.1))
        return disc_price


class Student(User):
    CITY_CHOICES = [('WS', 'Windsor'),
                    ('CG', 'Calgary'),
                    ('MR', 'Montreal'),
                    ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
    interested_in = models.ManyToManyField(Topic)

    # final project q10 (requires to "pip install Pillow" into the project folder to execute correctly)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/', null=True, blank=True)

    def __str__(self):
        return "{0} {1}".format(self.first_name, self.last_name)


class Order(models.Model):
    ORDER_STATUS = [(0, 'Cancelled'),
                    (1, 'Order Confirmed')]
    course = models.ForeignKey(Course, related_name="course", on_delete=models.CASCADE)
    levels = models.PositiveIntegerField(default=1)
    student = models.ForeignKey(Student, related_name="student", on_delete=models.CASCADE)
    order_status = models.IntegerField(choices=ORDER_STATUS, default=0)
    order_date = models.DateField()

    def __str__(self):
        return "{0} {1}".format(self.order_status, self.order_date)

    def total_cost(self):
        total = 0
        if self.course == Course.topic:
            total += Course.price
        else:
            total += 0
        return total

myapp/forms.py
from django import forms
from .models import Order
from django.core.validators import MinValueValidator
from django.core.validators import MinValueValidator
from .models import Order

'''
# Lab 9 - Login form
class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput, label='Username')
    password = forms.CharField(widget=forms.PasswordInput, label='Password')
'''

class InterestForm(forms.Form):
    CHOICES = [
        (1, "Yes"),
        (0, "No")
    ]
    interested = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    levels = forms.IntegerField(widget=forms.NumberInput, initial=1, validators=[MinValueValidator(1)])
    comments = forms.CharField(widget=forms.Textarea, label='Additional Comments', required=False)


# Lab 8 - Order Model Form
class OrderForm(forms.ModelForm):
    levels = forms.IntegerField(widget=forms.NumberInput, initial=1, validators=[MinValueValidator(1)])

    class Meta:
        model = Order
        fields = ['student', 'course', 'levels', 'order_date']
        # Set widgets
        widgets = {
            'student': forms.RadioSelect(),
            'order_date': forms.SelectDateWidget(),
        }

myapp/views.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .forms import OrderForm, InterestForm
from .models import Topic, Course, Student, Order
from django.shortcuts import render
from .forms import OrderForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from datetime import datetime


# lab9 login view
def user_login(request):
    if request.method == 'POST':

        '''
        # lab 9 testing cookie
        
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            return HttpResponse("<h1>Test cookie worked</h1>")
        else:
            return HttpResponse("<h1>cookies not enables</h1>")
        '''

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                # store date and time in session
                request.session['last_login'] = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
                # set expiry to 1 hour
                # uncomment to set session expiry
                # request.session.set_expiry(3600)
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('<h1>Your account is disabled.</h1>')
        else:
            return HttpResponse('<h1>Invalid login details.</h1>')
    else:
       # request.session.set_test_cookie()
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    # logout(request)
    try:
        del request.session['last_login']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse(('myapp:index')))


# lab 9 my account
#@login_required
def myaccount(request):
    user = request.user     # get current user

    if user.is_authenticated:   # check if user logged in
        u = User.objects.get(username=user)
        try:
            student = Student.objects.get(username=u)
            orders = Order.objects.filter(student__id=student.id)
            topics = Student.objects.filter(username=u).values_list('interested_in__name', flat=True)

            return render(request, 'myapp/myaccount.html', {'student': student, 'orders': orders, 'topics': topics})

        except Student.DoesNotExist:
            return HttpResponse('<h1>You are not a registered student!</h1>')
    else:
        return HttpResponse('<h1>User not logged in!</h1>')


def index(request):
    if request.session.get('last_login', False):    # check if session exists
        msg = request.session['last_login']
        user = request.user
        islogged = True
    else:
        msg = 'Your last login was more than an hour ago'
        user = 'User'
        islogged = False

    top_list = Topic.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index.html', {'top_list': top_list, 'msg': msg, 'user': user, 'islogged': islogged})


# about view
def about(request):

    if request.session.get('last_login', False):
        user = request.user
    else:
        user = 'User'

    if request.COOKIES.get('about_visits'):     # check if cookie exists
        visits = int(request.COOKIES.get('about_visits')) + 1   # increment number of visits
        response = render(request, 'myapp/about.html', {'num_visits': visits, 'user': user})

    else:
        visits = 1
        response = render(request, 'myapp/about.html', {'num_visits': visits, 'user': user})

    response.set_cookie('about_visits', visits, max_age=300)  # set cookie with updated value and age of 5 mins
    return response


# detail view
def detail(request, top_no):

    if request.session.get('last_login', False):
        user = request.user
    else:
        user = 'User'

    top = Topic.objects.filter(id=top_no)
    get_object_or_404(top)  # gives 404 error if id not found
    course_list = Course.objects.filter(topic__name=str(top.get().name))
    return render(request, 'myapp/detail.html', {'top_obj': top.get(),
                                                  'course_list': course_list, 'user': user})


# updated till lab 6
def courses(request):

    if request.session.get('last_login', False):
        user = request.user
    else:
        user = 'User'

    courlist = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'courlist': courlist, 'user': user})


# Lab 8 - place order view
def place_order(request):
    msg = ''
    courlist = Course.objects.all()


    if request.session.get('last_login', False):
        user = request.user
    else:
        user = 'User'


    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.levels <= order.course.stages:
                order.save()
                msg = 'Your course has been ordered successfully.'
                if order.course.price > 150.00:     # check if price > $150
                    order.course.price = order.course.discount()    # apply discount

            else:
                msg = 'You exceeded the number of levels for this course.'
            return render(request, 'myapp/order_response.html', {'msg': msg, 'user': user})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'courlist': courlist, 'user': user})


# Lab 8 - course detail view
def coursedetail(request, cour_id):
    msg = ''
    course = Course.objects.get(id=cour_id)

    if request.session.get('last_login', False):
        user = request.user
    else:
        user = 'User'

    if not course.for_everyone:
        msg = 'This course is not for everyone'

    if request.method == 'POST':    # if method is POST
        form = InterestForm(request.POST)
        if form.is_valid():   # check if form is valid
            is_interested = int(form.cleaned_data['interested'])
            course.interested += is_interested  # increment interested in db
            course.save()           # save db
            return HttpResponseRedirect('/myapp/')  # redirect to main page
    else:   # if method is GET
        form = InterestForm()
    return render(request, 'myapp/coursedetail.html', {'course': course, 'msg': msg, 'form': form, 'user': user})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

<h1>{% block myhdg %}Hello {{ user }}{% endblock %}</h1>
{% block body_block %}

    <h2 fontWeight="bold">This is an E-learning Website! Search our Topics to find all available
                   courses.</h2>

    <br>

    <p><em>Number of visits: {{ num_visits }}</em></p>

{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>

<h2 fontWeight="bold">This is an E-learning Website! Search our Topics to find all available '
                   'Courses.</h2>
<p><a href="/myapp">Main page (Hardcoded)</a></p> <!-- hardcoded -->
<p><a href="{% url 'myapp:index' %}">Main page (URL  Namespacing)</a></p> <!-- url namespacing -->

</body>
</html>

myapp/templates/myapp/base.html
<!-- base -->

<!DOCTYPE html>
{% load static %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
<title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>
<div>
<h1>{% block myhdg %}Hello User{% endblock %}</h1>
{% block body_block %} *** {% endblock %}
</div>
<hr />
<div class="links">
    {% block links %}
    <ul>
        <li class="hbar1"><a href="/myapp/about/">Find out about our E-Learning site</a></li>
        <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a></li>
        <li class="hbar1"><a href="{% url 'myapp:courses' %}">Click here to go to courses</a><br/></li>
        <li class="hbar1">{% block login %}{% endblock %}<br/></li>
    </ul>
    {% endblock %}
</div>
</body>
</html>

myapp/templates/myapp/coursedetail.html
{% extends 'myapp/base.html' %}

<!-- page to display course details and interest form -->
<h1>{% block myhdg %}Hello {{ user }}{% endblock %}</h1>
{% block body_block %}

    <!-- Container for detail page -->
    <div class="placeContainer">

        <!-- Container for course details -->
        <div class="detailContainer">
            <h2> Name: {{ course }} </h2> <br>
            <h2> Price: ${{ course.price }} </h2>
            <h2> Interested: {{ course.interested }}</h2>

            <p3>{{ msg }}</p3>      <!-- msg to display if course is not for everyone -->
        </div>

        <!-- container for interest form -->
        <div class="interestFormContainer">
            <form method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}     <!-- interest form -->
                </table>
                <div class="submitButton">
                    <input type="submit" value="Submit">    <!-- submit button -->
                </div>
            </form>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}

<!-- page to display list of courses -->

<h1>{% block myhdg %}Hello {{ user }}{% endblock %}</h1>

{% block body_block %}
    <h2> List of available courses: </h2>
    {% for available_course in courlist %}
       <p>
           <a href="{% url 'myapp:coursedetail' available_course.id %}"> {{ available_course }} </a>
       </p>
    {% endfor %}
    <br>
    <!-- place order link -->
    <h2><a href="{% url 'myapp:place_order' %}">Place an order</a></h2>

{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

<h1>{% block myhdg %}Hello {{ user }}{% endblock %}</h1>

{% block body_block %}
<h1> Topic: {{ top_obj.name }} </h1> <br>
<h2> Category: {{ top_obj.category }} </h2>
<h2> Courses: </h2>
{% for course in course_list %}
    <p> {{ course }} </p>
{% endfor %}


{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
<h1> Topic: {{ top_obj }} </h1> <br>
<h2> Category: {{ top_obj.category }} </h2>
<h2> Courses: </h2>
{% for course in course_list %}
    <p> {{ course }} </p>
{% endfor %}

<p><a href="{% url 'myapp:index' %}">Main page</a></p> <!-- url  namespacing -->

</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

<h1>{% block myhdg %}Hello {{ user }}{% endblock %}</h1>
{% block body_block %}
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for top in top_list %}
                <li> <a href="{% url 'myapp:detail' top.id %}"> {{ top.name}} </a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}

    <p><em>Last Login: {{ msg }}</em></p>

{% endblock %}

{% block login %}

    {% if islogged %}
        <a href="{% url 'myapp:logout' %}">Logout</a>
    {% else %}
       <a href="{% url 'myapp:login' %}">Login</a>
    {% endif %}

{% endblock %}

myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    E-Learning WebApp!</title>
</head>
<body>
{% if top_list %}
    <h2>List of Topics</h2>
    <ol>

        {% for top in top_list %}
            <li><a href="{% url 'myapp:detail' top.id %}"> {{ top.name}} </a></li>
        {% endfor %} </ol>
{% else %}
    <strong>There are no available topics!</strong>
{% endif %}
<p><a href="/myapp/about">About page (Hardcoded)</a></p> <!-- hardcoded -->
<p><a href="{% url 'myapp:about' %}">About page (URL Namespacing)</a></p> <!-- url namespacing -->
</body>
</html>

myapp/templates/myapp/login.html
<!DOCTYPE html>
{% load static %}

<!-- Login page -->

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
        <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
    </head>
    <body>
        <h1>Login</h1>
        <form action="/myapp/login/" method="post">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username">
            <label for="password">Password</label>
            <input type="password" name="password">
            <input type="submit" value="login">
        </form>
    </body>
</html>

myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}

<!-- page to display list of courses -->

{% block myhdg %}   {% endblock %}
{% block body_block %}

    <!-- full name -->
    <h1>{{ student.first_name }} {{ student.last_name }}</h1>

    <!-- List of courses ordered -->
    <h3>Courses ordered:</h3>
    {% for order in orders  %}
        <p>{{order.course}}</p>
    {% endfor %}

    <br>

    <!-- List of topics interested in -->
    <h3>Interested in:</h3>
    {% for topic in topics  %}
        <p>{{ topic }}</p>
    {% endfor %}

{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

<!-- page to display order response after place order is submitted -->
<h1>{% block myhdg %}Hello {{ user }}{% endblock %}</h1>
{% block body_block %}
<h1> {{ msg }} </h1>

{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}

<!-- Page to display course list with prices and place order form -->

<h1>{% block myhdg %}Hello {{ user }}{% endblock %}</h1>

{% block body_block %}
    <h2> List of available courses: </h2>
    <div class="placeContainer">

        <!-- Container for course and price list -->
        <div class="courseContainer">

            <!-- List of available courses -->
            <div class="courseDiv">
                {% for available_course in courlist %}
                    <p> {{ available_course }} </p>
                {% endfor %}
            </div>

            <!-- List of prices -->
            <div class="priceDiv">
                {% for available_course in courlist %}
                    <p>${{ available_course.price }}</p>
                {% endfor %}
            </div>
        </div>

        <!-- Container for place order form -->
        <div class="formContainer">
            <h2> Place order: </h2>
            <form method="post">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}  <!-- place order form -->
                </table>
                <div class="submitButton">
                    <input type="submit" value="Submit"> <!-- submit button -->
                </div>
            </form>

        </div>
    </div>
{% endblock %}